# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [17]:
import numpy as np
x= np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

In [18]:
import numpy as np
y=np.zeros((3,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [23]:
import numpy as np
z=np.linspace(0,5,10)
print(z)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [29]:
import numpy as np
z=np.linspace(0,5,10 ,endpoint =False)
print(z)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [31]:
import numpy as np
h=np.eye(5,5)
print(h)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [38]:
import numpy as np
k=np.random.rand(4,4)
print(k)

[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]


---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [49]:
import numpy as np
x= np.arange(1,13)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [50]:
x.reshape((4,3))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [51]:
import numpy as np
l= np.arange(1,17)
print(l)
l.reshape((4,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [52]:
l.dtype

dtype('int64')

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [54]:
import numpy as np
v=np.arange(2,100,2)
print(v)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [59]:
import numpy as np
k= np.random.randint(10,50, ((6,6)))
print(k)


[[41 45 37 28 23 39]
 [21 32 47 21 31 43]
 [41 34 42 47 19 47]
 [36 17 18 31 18 38]
 [40 35 35 24 27 31]
 [23 43 14 33 40 38]]


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [63]:
import numpy as np
j= np.array([[1,2,3,5,6,7],[3,4,5,7,2,1],[2,8,7,94,3,4],[2,3,4,1,2,4]])
print(j)

[[ 1  2  3  5  6  7]
 [ 3  4  5  7  2  1]
 [ 2  8  7 94  3  4]
 [ 2  3  4  1  2  4]]


In [70]:
k[0,5]


39

In [73]:
k[1:3, 2:4]

array([[47, 21],
       [42, 47]])

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [87]:
import numpy as np
f= np.random.randint(10,50, ((6,6)))
print(f)
tot_sum=np.sum(f)
print("the tal sum is:",tot_sum)

[[48 46 42 19 11 47]
 [18 49 40 49 15 49]
 [42 44 34 17 29 47]
 [29 47 34 42 25 32]
 [43 47 12 19 24 47]
 [34 29 29 25 45 15]]
the tal sum is: 1224


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [91]:
import numpy as np
v= np.random.randint(10,50, ((6,6)))

tot_sum=np.sum(v)
print("the tal sum is:",tot_sum)

tot_mean=np.mean(v)
print("the tal mean is:",tot_mean)

tot_median=np.median(v)
print("the total median is:",tot_median)

tot_sd=np.std(v)
print("the total sd is:",tot_sd)


the tal sum is: 988
the tal mean is: 27.444444444444443
the total median is: 28.0
the total sd is: 12.1184992755439


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [95]:
import numpy as np
np.random.seed(100)
z= np.random.randint(10,50, ((6,6)))

maximum=np.max(z)
print("the maximum is:",maximum)

manimum=np.min(z)
print("the manimum is:",manimum)

the maximum is: 49
the manimum is: 11


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [108]:
import numpy as np
np.random.seed(300)
p= np.random.randint(100,size=20)
print(p)
print('\n======================================')
c=np.argmax(p)
print(c)

[81 97 21 74  9 85 91 22 41 76 94 60  3 94 51 99 84 64 98 19]

15


---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [112]:
import numpy as np
np.random.seed(300)
d= np.random.randint(100,size=20)[::-1]
print(d)



[19 98 64 84 99 51 94  3 60 94 76 41 22 91 85  9 74 21 97 81]


In [115]:
import numpy as np
np.random.seed(300)
d= np.random.randint(100,size=20)
print(d)
np.flip(d)

[81 97 21 74  9 85 91 22 41 76 94 60  3 94 51 99 84 64 98 19]


array([19, 98, 64, 84, 99, 51, 94,  3, 60, 94, 76, 41, 22, 91, 85,  9, 74,
       21, 97, 81])

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [129]:
import numpy as np
np.random.seed(300)
m=np.random.randint(1,20,((3,3)))
l=np.random.randint(1,20,((3,3)))

print(m)
print(l)
o=np.multiply(m,l)
print(o)

[[18  2 11]
 [11 10  8]
 [10 13 19]]
[[ 4  4  1]
 [ 3  6 13]
 [18 10 10]]
[[ 72   8  11]
 [ 33  60 104]
 [180 130 190]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [127]:
import numpy as np
v = np.array([1, 2, 3, 4])
diagonal_matrix = np.diag(v)

print(diagonal_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [128]:
import numpy as np
np.random.seed(300)
m=np.random.randint(1,20,((3,3)))
l=np.random.randint(1,20,((3,3)))

print(m)
print(l)
o=np.dot(m,l)
print(o)

[[18  2 11]
 [11 10  8]
 [10 13 19]]
[[ 4  4  1]
 [ 3  6 13]
 [18 10 10]]
[[276 194 154]
 [218 184 221]
 [421 308 369]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [132]:
import numpy as np
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
y = matrix.flatten()
print(y)

[1 2 3 4 5 6]


---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [133]:
import numpy as np
x= np.array([1, 2, 3])
y= np.array([4, 5, 6])
z = np.vstack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [134]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
p = np.hstack((x, y))
print(p)

[1 2 3 4 5 6]


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [137]:
import numpy as np
x= np.array([1, 2, 3, 4, 5, 6])
k= np.split(x, 3)
print(k)

[array([1, 2]), array([3, 4]), array([5, 6])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [140]:
import numpy as np
y= np.random.random(5)
h= np.round(y, 2)
print(h)

[0.16 0.51 0.52 0.35 0.3 ]


---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [142]:
import numpy as np
x= np.array([1, 2, 2, 3, 4, 4, 5])
y= np.unique(x)
print(y)

[1 2 3 4 5]


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

In [143]:
import numpy as np
c= np.array([1, 3, 5, 7, 9])
c[c < 5] = 5
print(c)

[5 5 5 7 9]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---